### ISSUE TITLE
[TASK] - Tab keuze wordt bepaald via href

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-tabs#2]
is het gebruik van href om de active tab te bepalen wel gewenst ?
- single page apps die routing doen via de # truk zijn hier door geimpacteerd lijkt mij
- dit lijkt mij ook niet echt contained, daar er global scope gebruikt wordt

Code die dit gebruikt kan in tabs.js gevonden worden

```         
  var currentTabHash = window.location.hash;
  var activeTab = tabsContainer.querySelector("[href$='".concat(currentTabHash, "']"));
```

Ter info, als je nu naar de demo pagina gaat van webuniversum merk je direct wat het probleem is, je gaat dan altijd terug naar de hoofdpagina van de componenten als je van tab wilt wisselen.

**Comment by coemans** [comment]
Het klopt inderdaad dat dit voor problemen kan zorgen bij SPA die de # truc toepassen.

In het kader van clean URL's concludeer ik dat het gebruik van de # truc bij SPA eigenlijk best niet (meer) toegepast wordt. In dat opzicht zou het gebruik van een # om een sectie (tab) aan te duiden binnen één pagina valid zijn. Ik denk dat we dit best intern terugkoppelen en eerst bespreken hoe we routing voorzien bij SPA en in uitbreiding bij al onze toepassingen. Afhankelijk daarvan kunnen we dit issue verder oppikken of centraal bespreekbaar maken.

**Comment by pharacyde** [comment]
ik heb ook gemerkt dat die hash ook gebruikt wordt bij vl-collapsible en vl-info-tile. Ik vermoed dat dit is om die collapsible of info tile direct open te krijgen ? Dus die componenten kunnen we dan best niet combineren ?

**Comment by coemans** [comment]
Ik vermoed dat dit geen problemen gaat geven als er geen duplicate hashes zijn, maar te verifiëren/testen voor de zekerheid.
