### ISSUE TITLE
[BUG] - Demo pagina lijkt incorrect

### ISSUE THREAD

**Issue by stefanborghys** [milieuinfo/webcomponent-vl-ui-tabs#26]
**Omschrijf het probleem**
Ik had voor aanvang van een implementatie even de classes en domo pagina bekeken van deze component.
Maar het lijkt dat er de demo pagina iets mis gaat, kan dat?
Ben namelijk niet vertrouwd met deze component.

**Hoe te reproduceren**
zie: https://webcomponenten.omgeving.vlaanderen.be/demo/vl-tabs.html 

**Screenshots**
![vl-tabs-voorbeeld](https://user-images.githubusercontent.com/1375279/115709630-b9df8e80-a371-11eb-9818-2f9ae1f297c3.png)

Demo lokaal geserveerd:
![vl-tabs-voorbeeld-lokaal](https://user-images.githubusercontent.com/1375279/115710647-e0ea9000-a372-11eb-8c0b-32d8cc06d8e5.png)

**Comment by coemans** [comment]
Zal opgelost zijn bij volgende release en deploy van de BOM, ik sluit issue alvast af.

**Comment by stefanborghys** [comment]
ok, perfect
