### ISSUE TITLE
[BUG] - Getters voor id en title zorgen voor problemen bij vl-tabs-pane

### ISSUE THREAD

**Issue by pascalriquier** [milieuinfo/webcomponent-vl-ui-tabs#27]
**Omschrijf het probleem**
Getters voor id en title zorgen voor problemen bij vl-tabs-pane. Doordat er voor de "tab-id" en de "tab-titel" op de VlTabsPane class getters zijn gemaakt die clashen met native "id" en "title" attributen is het gedrag onvoorspelbaar als je via tabs maakt met data-vl-title en data-vl-id. 

**Hoe te reproduceren**
vl-tabs-pane maken met data-vl-id en data-vl-title

**Gewenst gedrag**
getters voor id en title op vl-tabs-pane niet laten clashen met native stuff

**Comment by stefanborghys** [comment]
@pascalriquier ik liep in de voortoets voor de 'slotted' tabs tegen een (gelijkaardig) probleem. De vl-tabs-pane krijgt in de methode __moveTabPaneTitleSlot() als id 'null' terug waardoor het slot niet de juiste benaming krijgt en deze dus als titel niet functioneerd. 

Nu ik was eens gaan kijken naar de onderliggende getAttribute('...') methode die zowel voor get id als title gebruikt worden. Als ik daarvoor de vl-ui-core raadpleeg zie ik dat deze al een mechanisme voorziet om de prefix te hanteren voor een attribuut en indien niets gevonden, terug valt op de meegegeven naam.
Nu in vl-tabs-pane zetten we wel al de prefix: this.getAttribute('data-vl-id') en this.getAttribute('data-vl-title'). Het lijkt me dat deze hier niet nodig is gezien die al vervat zit in de bovenliggende core getAttribute methode. 

@coemans klopt mijn redenering en is dit probleem simpel te fixen door 'data-vl-' weg te laten?
Of zijn er nog andere redeneren waarom we hier zo werken?

Gerelateerd aan: https://www.milieuinfo.be/jira/browse/VOORTOETS-3846

**Comment by coemans** [comment]
Op core niveau zit een fallback omdat initieel attributen rechtstreeks gebruikt werden zonder prefix `data-vl`. Dit kan echter voor problemen zorgen in combinatie met native attributen met dezelfde naam. Om niet te breken met voorgaande code werd de fallback voorzien.

Het probleem hier wordt niet veroorzaakt door de fallback maar wel door het overschrijven van de `id` en `title` getters. Deze getters kunnen bijgevolg best hernoemd worden.
