### ISSUE TITLE
[BUG] - Actieve tab query selector issue

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-tabs#3]
De query selector om te actieve tab te zoeken lijkt te strikt. Die zoekt achter een exact match op href ipv te zoeken om een href die eindigt met #uwTabKeuze

upstream wordt volgende selector gebruikt
```
          var activeTab = tabsContainer.querySelector("[href='".concat(currentTabHash, "']"));
```

hetgeen wel werkt is volgende selector 
```
          var activeTab = tabsContainer.querySelector("[href$='".concat(currentTabHash, "']"));
```
dus de href property krijgt een $ erbij om aan te geven dat het moet eindigen met de hash.  Dit omdat we niet altijd weten hoe een SPA zijn url gaat opbouwen.

**Comment by coemans** [comment]
Afhankelijk van de uitkomst van #2 kan deze uitbreiding inderdaad centraal toegevoegd worden. In kader van #2 verder te bespreken of het gebruik van meerdere #'s in een URL gewenst is. Afhankelijk van de uitkomst is de uitbreiding noodzakelijk of optioneel.
