### ISSUE TITLE
[BUG] - Infinite loop als default tab in de url aanwezig is

### ISSUE THREAD

**Issue by pharacyde** [milieuinfo/webcomponent-vl-ui-tabs#5]
Voorlopig enkel gemerkt met SPA die ook een router hebben. Maar wanneer een default tab in de url aanwezig is, wordt de activeTab geclickt via code. Die click zorgt dan voor een extra click om de responsive button (die je vaak niet ziet). Voor 1 of andere reden triggert die tweede click terug een click op de activeTab. 

Code snippets die van belang zijn

Active tab clicken:
```
          if (activeTab) {
            activeTab.click();
          } // only add click & focus listeners to tabs when there are panes to toggle
```
Dit triggert dan de click event handler
```
         tab.addEventListener('click', function () {
              // event.preventDefault();
              // reset tabs & panes
              _this.resetTabIndexesForTabs(tabs);
              _this.resetTabPanes(tabPanes); // set tab
              _this.showTabPaneForTab(tab, tabPanes[index]); // set responsive button label
              _this.updateResponsiveBtnLabelForTabsContainerWithTab(tabsContainer, tab);

              var toggleBtnEl = tabsContainer.querySelector("[".concat(tabToggleAtt, "]"));
              toggleBtnEl.click();
            });
```
De toggleBtnEl triggert dan terug het selecteren van de active tab en dus krijg je een loop. 

Voorlopig als we de active tab click als volgt schrijven, is de loop weg.
```
          if (activeTab) {
            setTimeout(() => activeTab.click(), 0);
          } // only add click & focus listeners to tabs when there are panes to toggle

```
cfr de setTimeout is toegevoegd

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2215
