### ISSUE TITLE
[BUG] - Responsiveness houdt geen rekening met smalle containers (vb: vl-maps-side-sheet)

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-tabs#7]
De tabs van de vl-tabs veranderen in een dropdown afhankelijk van schermbreedte. Die responsiveness lijkt echter alleen gebaseerd te zijn op de schermbreedte, in plaats van op de breedte van de tabs of de beschikbare ruimte.

Als je de tabs component in een smalle container zet (vb een vl-maps-side-sheet) dan zullen de tabs wrappen lang voordat de responsive layout er een dropdown van maakt:

<img width="342" alt="image" src="https://user-images.githubusercontent.com/58428396/105690429-46f28300-5efc-11eb-8adf-c3c3e2f18ad0.png">

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2218
