### ISSUE TITLE
[BUG] - Captured keyboard input, zelfs als de tabs geen focus hebben

### ISSUE THREAD

**Issue by FreekRombauts** [milieuinfo/webcomponent-vl-ui-tabs#8]
Indien een tab focus heeft kan je tussen de tabs navigeren met pijltjes-toetsen (links/rechts). Dit zou alleen mogen werken als de tab-strip focus heeft. Maar dit gebeurt ook als andere velden (vb een input veld) focus heeft.

Het gevolg is dat een input veld selecteren en met de pijltjes-toetsen de cursor verplaatsen in de plaats daarvan de actieve tab wisselt.

voorbeeld:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/58428396/105690854-c7b17f00-5efc-11eb-819d-44b0e09b9152.png">

in dit input veld staat de cursor focus tussen de letter c en d. Pijltjes-toetsen gebruiken geeft navigatie naar andere tab ipv verplaatsen van de cursor:

<img width="488" alt="image" src="https://user-images.githubusercontent.com/58428396/105690968-f0d20f80-5efc-11eb-8feb-7e9b303c5868.png">

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2217
